subarch: loong
version_stamp: systemd-20211001
target: stage2
rel_type: default
profile: loongson:desktop/3a5000/systemd
snapshot: 20211001
source_subpath: default/stage1-loong-systemd-20211001
compression_mode: pixz_x
portage_overlay: /var/gentoo/repos/loongson-overlay
portage_confdir: /opt/la-releng/portage/stages
